"""
Django settings for accessoneapi project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

mimetypes.add_type("text/css", ".css", True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*@wfh=dke&kks_v%5d!s=t%1@==lihksg#5uu-wym5)v!k5xay'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '102.37.42.50', 'connect.s-onedigital.com']
ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOWED_ORIGINS = [
#     "http://vms.s-onedigital.com"
# ]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://\w+\.vms.s-onedigital\.com$",
# ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'corsheaders',
    # 'django_crontab',
    # 'fcm_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
print(BASE_DIR)
#'>> '+os.path.join(BASE_DIR,'log/debug7.log')
# CRONJOBS = [
#     ('*/1 * * * *', 'app.cron.my_scheduled_job', '>> /tmp/scheduled_job.log')
# ]

ROOT_URLCONF = 'accessoneapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# FCM_DJANGO_SETTINGS = {
#         "FCM_SERVER_KEY": "AAAA-K-cxJQ:APA91bF1xSQNwhB0VaDhCsCdTjA1bqyCwLGOk84MqR0boYfbVt3d5RpRbu3dBwleeG8tEPYkCxbcYvSyft-xSzzlRBSz9gLhGs0uLvxR34p6ribIYnWo4mstp0eCLuU4woiE9msr84ui"
# }

WSGI_APPLICATION = 'accessoneapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'accessone-api',
#         'USER': 'accessone-api',
#         'PASSWORD': 'Ab5WnYzR8EkAyPBA',
#         'HOST': '/tmp/mysql.sock',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Indian/Mauritius'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'

STATIC_URL = '/static/'
# STATIC_ROOT = '/static'
STATIC_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static'

MEDIA_URL = '/media/'
# MEDIA_ROOT = '/media'
# MEDIA_ROOT = '/home/dev/accessone-api/media'
MEDIA_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/media'
