# Generated by Django 3.1.1 on 2020-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200923_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id_passport_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='parent_user',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='parent_user_url',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='passcode',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='vehicle_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appusertypes',
            name='app_user_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='residence',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='residenceareas',
            name='code',
            field=models.CharField(blank=True, default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='residenceareas',
            name='code_for_app',
            field=models.CharField(blank=True, default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='residencetype',
            name='residence_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='block_zone',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id_passport_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=1696, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='residence_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='street_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='resident',
            name='vehicle_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='code',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vehicle_number',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='visitoraccesstypes',
            name='access_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitoraccesstypes',
            name='main_account',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitortype',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitortype',
            name='visitor_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='visitorvalidity',
            name='visitor_validity',
            field=models.CharField(default='', max_length=120),
        ),
    ]
