# Generated by Django 3.1.1 on 2020-09-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200923_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='resident',
            name='location',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='address',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='resident',
            name='block_zone',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=8264, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='residence_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_area', to='app.residenceareas'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='residence_number',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
