# Generated by Django 3.1.1 on 2020-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200925_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=4299, max_length=120, unique=True),
        ),
    ]
