# Generated by Django 3.1.1 on 2020-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200930_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='validity_description',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=9491, max_length=120, unique=True),
        ),
    ]
