# Generated by Django 3.1.1 on 2020-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201002_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccesstypes',
            name='can_edit_agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitoraccesstypes',
            name='can_view_agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=3369, max_length=120, unique=True),
        ),
    ]
