# Generated by Django 3.1.1 on 2020-10-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201008_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='qr_code_share',
            field=models.ImageField(blank=True, upload_to='visitor_qr_codes'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=3392, max_length=120, unique=True),
        ),
    ]
