# Generated by Django 3.1.2 on 2020-10-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201017_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=5910, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Inouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('override', models.BooleanField(default=False)),
                ('checkin_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inouts_agent_checkin', to='app.appuser')),
                ('checkout_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inouts_agent_checkout', to='app.appuser')),
                ('inoutpass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inouts_status', to='app.visitor')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inouts_status', to='app.status')),
            ],
            options={
                'verbose_name': 'Inout',
                'verbose_name_plural': 'Inouts',
            },
        ),
    ]
