# Generated by Django 3.1.1 on 2020-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201028_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=4278, max_length=120, unique=True),
        ),
    ]
