# Generated by Django 3.1.7 on 2021-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201028_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='overrides_note',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=3442, max_length=120, unique=True),
        ),
    ]
