# Generated by Django 3.1.7 on 2021-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210323_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitortype',
            name='isPermanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=5223, max_length=120, unique=True),
        ),
    ]
