# Generated by Django 3.1.7 on 2021-03-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210325_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='overrides_note',
        ),
        migrations.AddField(
            model_name='visitor',
            name='overrides_note',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=6835, max_length=120, unique=True),
        ),
    ]
