# Generated by Django 3.1.7 on 2021-03-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210327_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='recurrance_str',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=9572, max_length=120, unique=True),
        ),
    ]
