# Generated by Django 3.1.7 on 2021-03-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210328_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=1903, max_length=120, unique=True),
        ),
    ]
