# Generated by Django 3.1.7 on 2021-03-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210328_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=8341, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='overrides_note',
            field=models.TextField(blank=True, default='', max_length=1200, null=True),
        ),
    ]
