# Generated by Django 3.1.7 on 2021-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210330_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='recurrance_str',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=6034, max_length=120, unique=True),
        ),
    ]
