# Generated by Django 3.1.7 on 2021-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210402_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=1024, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profiles/profile-placeholder.png', null=True, upload_to='profiles'),
        ),
    ]
