# Generated by Django 3.1.7 on 2021-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210403_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='passcode',
            field=models.CharField(blank=True, default=7868, max_length=120, unique=True),
        ),
    ]
